### ISSUE TITLE
Invalid hosts usage for non-sqlite

### ISSUE THREAD

**Issue by vitaly-t** [rucken/schematics#3]
https://github.com/rucken/schematics/blob/3221c457b06cd1580c3b1e8ad4137e66fe4070e1/fixtures/nestjs/entity/ormconfig.js#L31

You are correctly using `hosts` above, and then incorrectly here. There is no `host` or `port` on the root, there is only array `hosts`.

**Comment by EndyKaufman** [comment]
Thanks, fix in version 3.2.0
https://github.com/rucken/schematics/blob/develop/src/nestjs/new/files/__root__/ormconfig.__js__#L52
